namespace Imagin.Common
{
    public enum ThemeKeys
    {
        Accent,
        AccentLight,
        AccentDark,
        //...
        AccentForeground,
        //...
        Green,
        Red,

        ResultError,
        ResultMessage,
        ResultSuccess,
        ResultWarning,
        //...
        AngleControlBackground,
        AngleControlNeedleStroke,
        AngleControlOriginFill,
        AngleControlOriginStroke,
        //...
        Border,
        //...
        ButtonCancelBackground,
        ButtonCancelBorder,
        ButtonCancelForeground,

        ButtonCancelMouseOverBackground,
        ButtonCancelMouseOverBorder,
        ButtonCancelMouseOverForeground,

        ButtonCancelPressedBackground,
        ButtonCancelPressedBorder,
        ButtonCancelPressedForeground,
        //...
        ButtonDefaultBackground,
        ButtonDefaultBorder,
        ButtonDefaultForeground,

        ButtonDefaultMouseOverBackground,
        ButtonDefaultMouseOverBorder,
        ButtonDefaultMouseOverForeground,

        ButtonDefaultPressedBackground,
        ButtonDefaultPressedBorder,
        ButtonDefaultPressedForeground,
        //...
        ButtonForeground,
        ButtonBackground,
        ButtonBorder,

        ButtonMouseOverForeground,
        ButtonMouseOverBackground,
        ButtonMouseOverBorder,

        ButtonMouseDownBackground,
        ButtonMouseDownBorder,
        ButtonMouseDownForeground,
        //...
        CalendarButtonOver,
        CalendarButtonSelected,
        CalendarButtonToday,
        //...
        CheckBoxBackground,
        CheckBoxBorder,
        CheckBoxTickFill,
        CheckBoxTickStroke,
        //...
        ClockAStroke,
        ClockBStroke,
        ClockCenterStroke,
        ClockHourStroke,
        ClockMinuteStroke,
        ClockSecondStroke,
        ClockIntermediateTickStroke,
        ClockMajorTickStroke,
        ClockMinorTickStroke,
        //...
        ComboBoxBackground,
        ComboBoxBorder,
        ComboBoxForeground,

        ComboBoxFocusBorder,

        ComboBoxMouseOverBackground,
        ComboBoxMouseOverBorder,
        ComboBoxMouseOverForeground,

        ComboBoxCheckedBackground,
        ComboBoxCheckedBorder,
        ComboBoxCheckedForeground,

        ComboBoxItemForeground,
        ComboBoxItemSelectedBackground,
        ComboBoxItemSelectedForeground,
        ComboBoxItemMouseOverBackground,
        ComboBoxItemMouseOverForeground,
        ComboBoxItemEvenBackground,
        ComboBoxItemOddBackground,
        //...
        DataGridBackground,
        DataGridBorder,
        //...
        DataGridGridLinesHorizontal,
        DataGridGridLinesVertical,
        //...
        DataGridSelectAllForeground,
        DataGridSelectAllMouseOverForeground,
        DataGridSelectAllPressedForeground,
        //...
        DataGridColumnHeaderBackground,
        DataGridColumnHeaderBorder,
        DataGridColumnHeaderForeground,
        DataGridColumnHeaderMouseOverBackground,
        DataGridColumnHeaderMouseOverBorder,
        DataGridColumnHeaderMouseOverForeground,
        DataGridColumnHeaderPressedBackground,
        DataGridColumnHeaderPressedBorder,
        DataGridColumnHeaderPressedForeground,
        DataGridColumnHeaderThumb,
        //...
        DataGridRowForeground,
        DataGridRowSelectedBackground,
        DataGridRowSelectedBorder,
        DataGridRowSelectedForeground,
        DataGridRowSelectedActiveBackground,
        DataGridRowSelectedActiveBorder,
        DataGridRowSelectedActiveForeground,
        DataGridRowEvenBackground,
        DataGridRowEvenBorder,
        DataGridRowOddBackground,
        DataGridRowOddBorder,
        DataGridRowMouseOverBackground,
        DataGridRowMouseOverBorder,
        //...
        DialogBackground,
        DialogBodyBackground,
        DialogFooterBackground,
        DialogTitleBackground,
        DialogTitleForeground,
        //...
        DockControlEmptyMarkerSourceColor,
        DockControlPrimaryMarkerBackground,
        DockControlPrimaryMarkerSourceColor,
        DockControlSecondaryMarkerSourceColor,
        DockControlSelectionBackground,
        DockControlSelectionBorder,
        //...
        DockDocumentButtonBackground,
        DockDocumentButtonBorder,
        DockDocumentButtonForeground,
        //...
        DockPanelButtonBackground,
        DockPanelButtonBorder,
        DockPanelButtonForeground,
        DockPanelButtonCheckedBackground,
        DockPanelButtonCheckedBorder,
        DockPanelButtonCheckedForeground,
        DockPanelButtonMouseOverBackground,
        DockPanelButtonMouseOverBorder,
        DockPanelButtonMouseOverForeground,
        //...
        DockPanelHeaderBackground,
        DockPanelHeaderBorder,
        DockPanelHeaderForeground,
        DockPanelHeaderMouseDownBackground,
        DockPanelHeaderMouseDownBorder,
        DockPanelHeaderMouseDownForeground,
        DockPanelHeaderMouseOverBackground,
        DockPanelHeaderMouseOverBorder,
        DockPanelHeaderMouseOverForeground,
        //...
        DropTargetBorder,
        //...
        ExpanderBackground,
        ExpanderBorder,
        //...
        GridSplitterBackground,
        //...
        GridViewBackground,
        GridViewBorder,
        //...
        GroupBoxBorder,
        GroupBoxForeground,
        //...
        Link,
        //...
        LineStroke,
        //...
        ListBoxBackground,
        ListBoxBorder,
        ListBoxIsFocusedBorderBrush,

        ListBoxItemBackground,
        ListBoxItemBorder,

        ListBoxItemMouseOverBackground,
        ListBoxItemMouseOverBorder,
        ListBoxItemMouseOverForeground,

        ListBoxItemSelectedBackground,
        ListBoxItemSelectedBorder,
        ListBoxItemSelectedForeground,

        ListBoxItemSelectedActiveBackground,
        ListBoxItemSelectedActiveBorder,
        ListBoxItemSelectedActiveForeground,

        ListBoxItemMatchedBackground,
        ListBoxItemMatchedBorder,
        ListBoxItemMatchedForeground,

        ListBoxItemEvenBackground,
        ListBoxItemEvenBorder,
        ListBoxItemOddBackground,
        ListBoxItemOddBorder,
        //...
        ImageElement,
        //...
        ImageButton,
        ImageButtonChecked,
        ImageButtonMouseOver,
        ImageButtonPressed,

        ImageButtonBackground,
        ImageButtonBorder,
        ImageButtonForeground,

        ImageButtonCheckedBackground,
        ImageButtonCheckedBorder,
        ImageButtonCheckedForeground,

        ImageButtonMouseOverBackground,
        ImageButtonMouseOverBorder,
        ImageButtonMouseOverForeground,

        ImageButtonPressedBackground,
        ImageButtonPressedBorder,
        ImageButtonPressedForeground,
        //...
        ImageToggleButtonCheckedBackground,
        ImageToggleButtonCheckedBorder,
        ImageToggleButtonCheckedForeground,

        ImageToggleButtonMouseOverBackground,
        ImageToggleButtonMouseOverBorder,
        ImageToggleButtonMouseOverForeground,

        ImageToggleButtonPressedBackground,
        ImageToggleButtonPressedBorder,
        ImageToggleButtonPressedForeground,
        //...
        MenuBackground,
        MenuForeground,

        MenuItemBackground,
        MenuItemBorder,
        MenuItemForeground,

        MenuItemCheckedBulletBackground,
        MenuItemCheckedMouseOverBulletBackground,

        MenuItemTopLevelHeaderMouseOverBackground,
        MenuItemTopLevelHeaderMouseOverBorder,
        MenuItemTopLevelHeaderMouseOverForeground,
        MenuItemTopLevelHeaderPressedBackground,
        MenuItemTopLevelHeaderPressedBorder,
        MenuItemTopLevelHeaderPressedForeground,

        MenuItemSubmenuHeaderBackground,
        MenuItemSubmenuHeaderBorder,
        MenuItemSubmenuHeaderForeground,
        MenuItemSubmenuHeaderMouseOverBackground,
        MenuItemSubmenuHeaderMouseOverBorder,
        MenuItemSubmenuHeaderMouseOverForeground,
        MenuItemSubmenuHeaderPressedBackground,
        MenuItemSubmenuHeaderPressedBorder,
        MenuItemSubmenuHeaderPressedForeground,

        MenuItemSubmenuItemBackground,
        MenuItemSubmenuItemBorder,
        MenuItemSubmenuItemForeground,
        MenuItemSubmenuItemMouseOverBackground,
        MenuItemSubmenuItemMouseOverBorder,
        MenuItemSubmenuItemMouseOverForeground,
        MenuItemSubmenuItemPressedBackground,
        MenuItemSubmenuItemPressedBorder,
        MenuItemSubmenuItemPressedForeground,
        //...
        PopupBackground,
        PopupBorder,
        PopupDropShadow,
        //...
        ProgressBarForeground,
        ProgressBarBackground,
        //...
        ProgressCircleForeground,
        //...
        PropertyGridDescriptionBackground,
        PropertyGridDescriptionBorder,
        //...
        RadioButtonBackground,
        RadioButtonBorder,
        RadioButtonForeground,
        RadioButtonTickStroke,
        //...
        RadioGroupMouseOverBackground,
        RadioGroupMouseOverForeground,
        RadioGroupCheckedBackground,
        RadioGroupCheckedForeground,
        //...
        RippleDecoratorBorder,
        //...
        RulerBackground,
        RulerBorder,
        RulerForeground,
        RulerTickStroke,
        //...
        ScrollBarBackground,
        ScrollBarMouseOverBackground,
        ScrollBarDraggingBackground,
        //...
        SelectionCanvasBorder,
        SelectionCanvasBackground,
        //...
        SliderThumbBackground,
        SliderThumbBorder,

        SliderDecreaseButtonBackground,
        SliderDecreaseButtonBorder,
        SliderIncreaseButtonBackground,
        SliderIncreaseButtonBorder,
        //...
        StatusBarBackground,
        StatusBarBorder,
        StatusBarForeground,
        //...
        SwipeButtonBackground,
        SwipeButtonBorder,
        SwipeButtonForeground,
        SwipeButtonCheckedBackground,
        SwipeButtonCheckedForeground,
        SwipeButtonMouseDownBackground,
        SwipeButtonMouseDownForeground,
        SwipeButtonMouseOverBackground,
        SwipeButtonMouseOverForeground,
        //...
        SwitchButtonBackground,
        SwitchButtonBorder,
        SwitchButtonForeground,
        SwitchButtonThumbBackground,
        SwitchButtonThumbBorder,
        SwitchButtonCheckedBackground,
        SwitchButtonCheckedBorder,
        SwitchButtonCheckedForeground,
        SwitchButtonCheckedThumbBackground,
        SwitchButtonCheckedThumbBorder,
        SwitchButtonNullBackground,
        SwitchButtonNullBorder,
        SwitchButtonNullForeground,
        SwitchButtonNullThumbBackground,
        SwitchButtonNullThumbBorder,
        //...
        TabControlBackground,
        TabControlBorder,
        TabControlBorderActive,

        TabItemBackground,
        TabItemBorder,
        TabItemForeground,
        TabItemSelectedBackground,
        TabItemSelectedBorder,
        TabItemSelectedForeground,
        TabItemMouseOverBackground,
        TabItemMouseOverBorder,
        TabItemMouseOverForeground,
        //...
        Text,
        //...
        TextBoxBackground,
        TextBoxBorder,
        TextBoxMouseOverBorder,
        TextBoxFocusedBackground,
        TextBoxFocusedBorder,
        TextBoxCaret,
        TextBoxSelection,
        TextBoxSelectionInactive,
        TextBoxDisabledSelection,
        //...
        ToolBarBackground,
        ToolBarBorder,
        ToolBarTrayBackground,
        //...
        ToolTipBackground,
        ToolTipBorder,
        ToolTipForeground,
        //...
        TreeViewBackground,
        TreeViewBorder,
        TreeViewFocusBorder,

        TreeViewLineStroke,

        TreeViewItemToggleButtonEmptyFill,
        TreeViewItemToggleButtonFilledFill,
        TreeViewItemToggleButtonFilledCheckedFill,

        TreeViewItemEvenBackground,
        TreeViewItemEvenBorder,
        TreeViewItemOddBackground,
        TreeViewItemOddBorder,

        TreeViewItemForeground,
        TreeViewItemMouseOverBackground,
        TreeViewItemMouseOverBorder,
        TreeViewItemMouseOverForeground,
        TreeViewItemSelectedBackground,
        TreeViewItemSelectedBorder,
        TreeViewItemSelectedForeground,
        TreeViewItemSelectedActiveBackground,
        TreeViewItemSelectedActiveBorder,
        TreeViewItemSelectedActiveForeground,
        //...
        WindowActiveBorder,
        WindowBackground,
        WindowBorder,
        WindowOverlayBackground,

        WindowHeaderBackground,
        WindowHeaderBorder,

        WindowContentBackground,
        WindowContentBorder,
        WindowContentBorderThickness,

        WindowButtonBorder,
        WindowButtonBackground,
        WindowButtonForeground,
        WindowButtonCheckedBorder,
        WindowButtonCheckedBackground,
        WindowButtonCheckedForeground,
        WindowButtonMouseOverBorder,
        WindowButtonMouseOverBackground,
        WindowButtonMouseOverForeground,
        WindowButtonPressedBorder,
        WindowButtonPressedBackground,
        WindowButtonPressedForeground,

        WindowFooterBackground,
        WindowFooterBorder,
    }
}