namespace Imagin.Common.Media
{
    /// <summary>
    /// Contains a list of all accent colors available in Windows 10 (names obtained from http://chir.ag/projects/name-that-color).
    /// </summary>
    public enum AccentColor
    {
        [Key("b146c2")]
        Amethyst,
        [Key("107c10")]
        Bilbao,
        [Key("038387")]
        BlueLagoon,
        [Key("0099bc")]
        BondiBlue,
        [Key("767676")]
        Boulder,
        [Key("ef6950")]
        BurntSienna,
        [Key("8e8cd8")]
        ChetwodeBlue,
        [Key("5d5a58")]
        Chicago,
        [Key("ff4343")]
        CoralRed,
        [Key("e81123")]
        Crimson,
        [Key("567c73")]
        CuttySark,
        [Key("f7630c")]
        Ectasy,
        [Key("0063b1")]
        Endeavour,
        [Key("9a0089")]
        Flirt,
        [Key("c239b3")]
        FuchsiaPink,
        [Key("4c4a48")]
        FuscousGray,
        [Key("647c64")]
        GladeGreen,
        [Key("da3b01")]
        Grenadier,
        [Key("e3008c")]
        HollywoodCerise,
        [Key("00cc6a")]
        Jade,
        [Key("2d7d9a")]
        JellyBean,
        [Key("7a7574")]
        LightBoulder,
        [Key("498205")]
        Limeade,
        [Key("c30052")]
        Lipstick,
        [Key("0078d7")]
        Lochmara,
        [Key("e74856")]
        Mandy,
        [Key("2980cc")]
        Mariner,
        [Key("486860")]
        MineralGreen,
        [Key("6b69d6")]
        MoodyBlue,
        [Key("525e54")]
        Nandor,
        [Key("69797e")]
        Nevada,
        [Key("018574")]
        Observatory,
        [Key("7e735f")]
        Pablo,
        [Key("00b294")]
        PersianGreen,
        [Key("d13438")]
        PersianRed,
        [Key("ff8c00")]
        Pizazz,
        [Key("ea005e")]
        Razzmatazz,
        [Key("bf0077")]
        RedViolet,
        [Key("4a5459")]
        RiverBed,
        [Key("00b7c3")]
        RobinsEggBlue,
        [Key("10893e")]
        Salem,
        [Key("881798")]
        Seance,
        [Key("ffb900")]
        SelectiveYellow,
        [Key("847545")]
        Shadow,
        [Key("515c6b")]
        ShuttleGray,
        [Key("68768A")]
        SlateGray,
        [Key("744da9")]
        Studio,
        [Key("ca5010")]
        TiaMaria,
        [Key("8764b8")]
        Wisteria
    }
}
